#!/bin/bash
#
# Title:      PlexGuide (Reference Title File)
# Author(s):  Bender
# URL:        https://plexguide.com - http://github.plexguide.com
# GNU:        General Public License v3.0

# READ FIRST
# BEFORE INSTALLING VARKEN, SET UP YOUR OTHER CONTAINERS THAT YOU WANT TO MONITOR (PLEX, SONARR, RADARR ETC)
# VARKEN NEEDS A DATABASE! ENSURE YOU HAVE ALREADY DEPLOYED INFLUXDB.  YOU ALSO NEED TO ADD YOUR VARKEN.INI FILE.
################################################################################
---
- name: Deploy varkin
  hosts: localhost
  gather_facts: False
  tasks:  
    - stat: path=/opt/appdata/varken/varken.example.ini
      register: varken_result

    - debug:
        msg: "File doesnt exist"
      when: varken_result.stat.exists == False

    - debug:
        msg: "File does exist, we can continue"
      when: varken_result.stat.exists == True
    
   # - fail:
    #    msg: "You need to add varken.example.ini"
     # when: varken_result.stat.exists == False
     

    - name: 'Set Known Facts'
      set_fact:
        pgrole: 'varken'
        image: 'boerderij/varken'

        # CORE (MANDATORY) ############################################################
    - name: 'Including cron job'
      include_tasks: '/opt/communityapps/apps/_core.yml'

    - name: 'Including folders'
      include_tasks: '/opt/communityapps/apps/_downloaders.yml'

    - name: 'Checking for existing app data'
      stat:
        path: /opt/appdata/{{pgrole}}/core.conf
      register: confcheck

    - name: 'Setting PG Volumes'
      set_fact:
        pg_volumes:
          - '/opt/appdata/{{pgrole}}:/config'
      #    - '/etc/localtime:/etc/localtime:ro'
    
    - name: 'Setting PG ENV'
      set_fact:
        pg_env:
          PUID: '1000'
          PGID: '1000'
    
    - name: 'Deploying {{pgrole}}'
      docker_container:
        name: '{{pgrole}}'
        image: '{{image}}'
        pull: yes
        volumes: '{{pg_volumes}}'
        env: '{{pg_env}}'
        restart_policy: unless-stopped
        networks:
          - name: plexguide
            aliases:
              - '{{pgrole}}'
        state: started  
    
 



    